---
traefik_version: "latest"
traefik_directory: "/opt/traefik"

traefik_debug_enable: true
traefik_log_level: "DEBUG"

# Main configuration
traefik_entrypoint_http_port: 80
traefik_entrypoint_http_redirect_to_https: false
traefik_entrypoint_https_port: 443

# Dashboard
traefik_dashboard_enable: true
traefik_dashboard_entrypoint_port: 8080
traefik_dashboard_subdomain: "traefik"
traefik_dashboard_basicauth_enable: false
traefik_dashboard_basicauth_users: []

# Docker
traefik_docker_enable: true
traefik_docker_domain: "yourdomain.tech"
traefik_docker_expose_by_default: false

# Enable automatic certificates from Let's Encrypt
traefik_acme_enable: false
traefik_acme_autocreate_from_host: true
traefik_acme_email: "levilugato@yourdomain.com.br"

# Consul Key-Value backend
traefik_consul_enable: false
traefik_consul_endpoint: "127.0.0.1:8500"
traefik_consul_prefix: "traefik"
traefik_consul_watch: true