- name: Create directory gitlab-runner
  become: yes
  file:
    path: /srv/gitlab-runner/config
    state: directory
    owner: sistemas
    group: sistemas
    mode: 0775

- name: Render gitlab-runner config
  become: yes
  template:
    src: config.toml.j2
    dest: "/srv/gitlab-runner/config/config.toml"

- name: get gitlab-runner run status
  shell: docker ps | grep -w "gitlab-runner"
  register: container_run_status
  become: yes
  failed_when: false

- name: Show exec output container 
  debug: msg="{{ container_run_status }}"

- name: pull the gitlab-runner image
  docker_image:
    name: "gitlab/gitlab-runner:latest"
  become: True

- name: Initiate Docker for Gitlab Runner
  docker_container:
    name: "gitlab-runner"
    image: "gitlab/gitlab-runner:latest"
    restart_policy: always
    volumes:
      - /srv/gitlab-runner/config:/etc/gitlab-runner:Z
      - /var/run/docker.sock:/var/run/docker.sock
    env: 
        REGISTRATION_TOKEN : "{{ REGISTRATION_TOKEN }}"
        ENVIRO : "{{ ENVIRO }}"
  register: docker_start_result
  when: container_run_status.rc != 0
  
  
- name: register runner gitlab-runner
  command: docker exec -it gitlab-runner bash -c 'gitlab-runner register --non-interactive -url https://gitlab.com/ --registration-token $REGISTRATION_TOKEN --executor docker --description $ENVIRO --tag-list $ENVIRO --docker-image "docker:latest" --run-untagged=false --docker-volumes /var/run/docker.sock:/var/run/docker.sock -c /etc/gitlab-runner/config.toml'
  register: runner_start_result
  when: container_run_status.rc != 0

- name: Show exec output
  debug: msg="{{ runner_start_result }}"